image: gcc:6.3

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf automake
  script:
    - autoreconf -vfi
    - ./configure LIBS="-lm -ldecnumber"
    - make
    - make check
    - make distcheck
