language: c
dist: trusty

os:
  - linux

compiler:
  - gcc

before_script:
  - autoreconf -vfi

script:
  - ./configure dfp754_LIBS=-ldfp || { cat config.log; false; }
  - make clean
  - make all
  - make check || { cat test/test-suite.log; false; }
  - make distcheck || { cat ttt-*/_build/test/test-suite.log; false; }

## whitelist
branches:
  only:
    - master

notifications:
  email:
    - devel@fresse.org
